blank_issues_enabled: true
contact_links:
  - name: ğŸ—’ï¸  Traffic Refinery README
    url: https://github.com/traffic-refinery/traffic-refinery#readme
    about: Consult the Traffic Refinery README first.
  - name: ğŸ“– Traffic Refinery Usage Information
    url: https://traffic-refinery.github.io/usage.html
    about: Learn more about how to use Traffic Refinery here.
